version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: minha_api
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_NAME: minha_api
      DB_USER: seu_usuario
      DB_PASS: sua_senha
      DB_HOST: postgres